# Generated by Django 3.1 on 2020-08-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20200823_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
    ]
